import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';

import { DEFAULT_PREFERENCES, STORAGE_KEYS } from '../constants';
import { StorageService } from '../storage/StorageService';
import type { AppLanguage, UserPreferences } from '../types';

type TranslationKey =
  | 'tabs.home'
  | 'tabs.ride'
  | 'tabs.contacts'
  | 'tabs.hospitals'
  | 'tabs.settings'
  | 'settings.title'
  | 'settings.appearance'
  | 'settings.safety'
  | 'settings.emergency'
  | 'settings.notifications'
  | 'settings.language'
  | 'settings.languageDescription'
  | 'settings.languageEnglish'
  | 'settings.languageHindi'
  | 'settings.languageGujarati'
  | 'settings.languageMarathi'
  | 'settings.languageTamil'
  | 'settings.languageTelugu'
  | 'settings.languageBengali'
  | 'settings.languageKannada'
  | 'settings.languageMalayalam'
  | 'settings.languagePunjabi'
  | 'settings.languageUrdu'
  | 'settings.languageSpanish'
  | 'settings.languageFrench'
  | 'settings.languageGerman'
  | 'settings.languageArabic'
  | 'settings.languageJapanese'
  | 'settings.languageChinese'
  | 'settings.themeDescription'
  | 'settings.crashSensitivity'
  | 'settings.crashSensitivityHint'
  | 'settings.low'
  | 'settings.medium'
  | 'settings.high'
  | 'settings.sosDelay'
  | 'settings.sosDelayDescription'
  | 'settings.autoShareLocation'
  | 'settings.autoShareLocationDescription'
  | 'settings.rideAutoStart'
  | 'settings.rideAutoStartDescription'
  | 'settings.offlineEmergencyMode'
  | 'settings.offlineEmergencyModeDescription'
  | 'settings.pushNotifications'
  | 'settings.pushNotificationsDescription'
  | 'settings.openDeviceSettings'
  | 'settings.openDeviceSettingsDescription'
  | 'settings.about'
  | 'settings.appVersion'
  | 'settings.expoSdk'
  | 'settings.architecture'
  | 'settings.architectureDescription'
  | 'settings.medicalId'
  | 'settings.medicalIdDesc'
  | 'settings.dangerZone'
  | 'settings.dangerZoneDescription'
  | 'settings.resetAllData'
  | 'settings.resetAlertTitle'
  | 'settings.resetAlertBody'
  | 'settings.cancel'
  | 'settings.resetEverything'
  | 'settings.done'
  | 'settings.resetDone'
  | 'settings.nightModeActive'
  | 'home.title'
  | 'home.rideActive'
  | 'home.readyToRide'
  | 'contacts.title'
  | 'contacts.add'
  | 'contacts.loading';

type TranslationTable = Partial<Record<TranslationKey, string>>;
type FullTranslationTable = Record<TranslationKey, string>;

const baseEnglishTranslations: FullTranslationTable = {
  'tabs.home': 'Home',
  'tabs.ride': 'Ride',
  'tabs.contacts': 'Contacts',
  'tabs.hospitals': 'Hospitals',
  'tabs.settings': 'Settings',
  'settings.title': 'Settings',
  'settings.appearance': 'APPEARANCE',
  'settings.safety': 'SAFETY',
  'settings.emergency': 'EMERGENCY',
  'settings.notifications': 'NOTIFICATIONS',
  'settings.language': 'Language',
  'settings.languageDescription': 'Choose the language used across the app',
  'settings.languageEnglish': 'English',
  'settings.languageHindi': 'Hindi',
  'settings.languageGujarati': 'Gujarati',
  'settings.languageMarathi': 'Marathi',
  'settings.languageTamil': 'Tamil',
  'settings.languageTelugu': 'Telugu',
  'settings.languageBengali': 'Bengali',
  'settings.languageKannada': 'Kannada',
  'settings.languageMalayalam': 'Malayalam',
  'settings.languagePunjabi': 'Punjabi',
  'settings.languageUrdu': 'Urdu',
  'settings.languageSpanish': 'Spanish',
  'settings.languageFrench': 'French',
  'settings.languageGerman': 'German',
  'settings.languageArabic': 'Arabic',
  'settings.languageJapanese': 'Japanese',
  'settings.languageChinese': 'Chinese',
  'settings.themeDescription':
    'Auto mode activates a high-contrast red-black night palette after 19:00 to reduce glare while riding.',
  'settings.crashSensitivity': 'Crash Detection Sensitivity',
  'settings.crashSensitivityHint': 'Higher sensitivity detects lighter impacts. Recommended: Medium.',
  'settings.low': 'Low',
  'settings.medium': 'Medium',
  'settings.high': 'High',
  'settings.sosDelay': 'SOS Auto-Send Delay',
  'settings.sosDelayDescription': 'Seconds before alert sends automatically',
  'settings.autoShareLocation': 'Auto-Share Location',
  'settings.autoShareLocationDescription': 'Include GPS coordinates in emergency alerts',
  'settings.rideAutoStart': 'Ride Auto-Start',
  'settings.rideAutoStartDescription': 'Begin monitoring automatically when motion is detected',
  'settings.offlineEmergencyMode': 'Offline Emergency Mode',
  'settings.offlineEmergencyModeDescription': 'Queue alerts locally when internet is unavailable',
  'settings.pushNotifications': 'Push Notifications',
  'settings.pushNotificationsDescription': 'Ride reminders and safety alerts',
  'settings.openDeviceSettings': 'Open Device Settings',
  'settings.openDeviceSettingsDescription': 'Manage notification permissions',
  'settings.about': 'ABOUT',
  'settings.appVersion': 'App Version',
  'settings.expoSdk': 'Expo SDK',
  'settings.architecture': 'Architecture',
  'settings.architectureDescription': 'Offline-first · TypeScript strict',
  'settings.medicalId': 'Emergency Medical ID',
  'settings.medicalIdDesc': 'View and edit critical health details shared during SOS',
  'settings.dangerZone': 'Danger Zone',
  'settings.dangerZoneDescription':
    'This permanently deletes all your contacts, ride history, and preferences. It cannot be undone.',
  'settings.resetAllData': 'Reset All App Data',
  'settings.resetAlertTitle': 'Reset App Data',
  'settings.resetAlertBody': 'This will delete all contacts, ride history, and preferences permanently.',
  'settings.cancel': 'Cancel',
  'settings.resetEverything': 'Reset Everything',
  'settings.done': 'Done',
  'settings.resetDone': 'All app data cleared.',
  'settings.nightModeActive': 'Night mode active · Red-black palette until 06:00',
  'home.title': 'Home',
  'home.rideActive': 'Ride Active',
  'home.readyToRide': 'Ready to ride',
  'contacts.title': 'Contacts',
  'contacts.add': 'Add',
  'contacts.loading': 'Loading contacts...',
};

const translations: Record<AppLanguage, TranslationTable> = {
  en: baseEnglishTranslations,
  hi: {
    'tabs.home': 'होम',
    'tabs.ride': 'राइड',
    'tabs.contacts': 'संपर्क',
    'tabs.hospitals': 'अस्पताल',
    'tabs.settings': 'सेटिंग्स',
    'settings.title': 'सेटिंग्स',
    'settings.appearance': 'सजावट',
    'settings.safety': 'सुरक्षा',
    'settings.emergency': 'आपातकालीन',
    'settings.notifications': 'सूचनाएं',
    'settings.language': 'भाषा',
    'settings.languageDescription': 'ऐप में उपयोग की जाने वाली भाषा चुनें',
    'settings.themeDescription': 'ऑटो मोड रात 19:00 बजे के बाद एक उच्च-विपरीत लाल-काले रंग की रात पैलेट को सक्रिय करता है।',
    'settings.crashSensitivity': 'क्रैश डिटेक्शन संवेदनशीलता',
    'settings.crashSensitivityHint': 'अधिक संवेदनशीलता हल्के प्रभावों का पता लगाती है। अनुशंसित: मध्यम।',
    'settings.low': 'कम',
    'settings.medium': 'मध्यम',
    'settings.high': 'उच्च',
    'settings.sosDelay': 'एसओएस ऑटो-भेजें देरी',
    'settings.sosDelayDescription': 'अलर्ट स्वचालित रूप से भेजने से पहले सेकंड',
    'settings.autoShareLocation': 'ऑटो-साझा स्थान',
    'settings.autoShareLocationDescription': 'आपातकालीन अलर्ट में जीपीएस निर्देशांक शामिल करें',
    'settings.rideAutoStart': 'राइड ऑटो-स्टार्ट',
    'settings.rideAutoStartDescription': 'गति का पता चलने पर स्वचालित रूप से निगरानी शुरू करें',
    'settings.offlineEmergencyMode': 'ऑफ़लाइन आपातकालीन मोड',
    'settings.offlineEmergencyModeDescription': 'इंटरनेट अनुपलब्ध होने पर अलर्ट स्थानीय रूप से कतारबद्ध करें',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.pushNotificationsDescription': 'राइड रिमाइंडर और सुरक्षा अलर्ट',
    'settings.about': 'के बारे में',
    'settings.medicalId': 'आपातकालीन मेडिकल आईडी',
    'settings.medicalIdDesc': 'एसओएस के दौरान साझा किए गए अपने चिकित्सा विवरण देखें और संपादित करें',
    'settings.dangerZone': 'खतरे का क्षेत्र',
    'settings.resetAllData': 'सभी ऐप डेटा रीसेट करें',
    'settings.cancel': 'रद्द करें',
    'settings.resetEverything': 'सब कुछ रीसेट करें',
    'settings.done': 'हो गया',
    'home.title': 'होम',
    'home.rideActive': 'सक्रिय राइड',
    'home.readyToRide': 'सवारी के लिए तैयार',
    'contacts.title': 'संपर्क',
    'contacts.add': 'जोड़ें',
    'contacts.loading': 'संपर्क लोड हो रहे हैं...',
  },
  gu: {
    'tabs.home': 'હોમ',
    'tabs.ride': 'રાઇડ',
    'tabs.contacts': 'સંપર્કો',
    'tabs.hospitals': 'હોસ્પિટલો',
    'tabs.settings': 'સેટિંગ્સ',
    'settings.title': 'સેટિંગ્સ',
    'settings.appearance': 'દેખાવ',
    'settings.safety': 'સુરક્ષા',
    'settings.emergency': 'કટોકટી',
    'settings.notifications': 'સૂચનાઓ',
    'settings.language': 'ભાષા',
    'settings.languageDescription': 'એપમાં ઉપયોગ થતી ભાષા પસંદ કરો',
    'settings.themeDescription': 'ઓટો મોડ રાત્રે 19:00 પછી હાઇ-કોન્ટ્રાસ્ટ લાલ-કાળી નાઇટ પેલેટ સક્રિય કરે છે.',
    'settings.crashSensitivity': 'ક્રેશ સેન્સિટિવિટી',
    'settings.crashSensitivityHint': 'ઉચ્ચ સંવેદનશીલતા હળવા અકસ્માત પણ શોધી શકે છે. ભલામણ કરેલ: મધ્યમ.',
    'settings.low': 'નીચી',
    'settings.medium': 'મધ્યમ',
    'settings.high': 'ઉચ્ચ',
    'settings.sosDelay': 'SOS ઓટો-મોકલો વિલંબ',
    'settings.sosDelayDescription': 'એલર્ટ આપમેળે મોકલવા માટે સેકન્ડો',
    'settings.autoShareLocation': 'લોકેશન શેરિંગ ઓટો',
    'settings.autoShareLocationDescription': 'કટોકટી એલર્ટમાં જીપીએસ લોકેશન શામેલ કરો',
    'settings.rideAutoStart': 'રાઇડ ઓટો-સ્ટાર્ટ',
    'settings.rideAutoStartDescription': 'ગતિ જણાય ત્યારે આપમેળે મોનિટરિંગ શરૂ કરો',
    'settings.offlineEmergencyMode': 'ઓફલાઇન ઇમરજન્સી મોડ',
    'settings.offlineEmergencyModeDescription': 'ઇન્ટરનેટ ન હોય ત્યારે એલર્ટ લોકલી સેવ કરો',
    'settings.pushNotifications': 'પુશ સૂચનાઓ',
    'settings.pushNotificationsDescription': 'રાઇડ રિમાઇન્ડર અને સુરક્ષા એલર્ટ',
    'settings.about': 'વિશે',
    'settings.medicalId': 'કટોકટી મેડિકલ ID',
    'settings.medicalIdDesc': 'કટોકટીમાં શેર કરેલી તબીબી વિગતો જુઓ અને એડિટ કરો',
    'settings.dangerZone': 'ડેન્જર ઝોન',
    'settings.resetAllData': 'તમામ એપ ડેટા રીસેટ કરો',
    'settings.cancel': 'રદ કરો',
    'settings.resetEverything': 'બધું રીસેટ કરો',
    'settings.done': 'પૂર્ણ',
    'home.title': 'હોમ',
    'home.rideActive': 'રાઇડ એક્ટિવ છે',
    'home.readyToRide': 'રાઇડ માટે તૈયાર',
    'contacts.title': 'સંપર્કો',
    'contacts.add': 'ઉમેરો',
    'contacts.loading': 'સંપર્કો લોડ થઈ રહ્યા છે...',
  },
  mr: {
    'tabs.home': 'होम',
    'tabs.ride': 'राइड',
    'tabs.contacts': 'संपर्क',
    'tabs.hospitals': 'रुग्णालय',
    'tabs.settings': 'सेटिंग्ज',
    'settings.title': 'सेटिंग्ज',
    'settings.appearance': 'देखावा',
    'settings.safety': 'सुरक्षितता',
    'settings.emergency': 'आणीबाणी',
    'settings.notifications': 'सूचना',
    'settings.language': 'भाषा',
    'settings.languageDescription': 'अॅपची भाषा निवडा',
    'settings.themeDescription': 'रात्री १९:०० नंतर हाय-कॉन्ट्रास्ट लाल-काळा नाईट पॅलेट स्वयंचलितपणे सक्रिय होईल.',
    'settings.crashSensitivity': 'अपघात संवेदनशीलता',
    'settings.crashSensitivityHint': 'जास्त संवेदनशीलता हलके धक्के शोधते. शिफारस केलेले: मध्यम.',
    'settings.low': 'कमी',
    'settings.medium': 'मध्यम',
    'settings.high': 'उच्च',
    'settings.sosDelay': 'SOS ऑटो-पाठवण्यास विलंब',
    'settings.sosDelayDescription': 'इशारा स्वयंचलितपणे जाण्यापूर्वीचे सेकंद',
    'settings.autoShareLocation': 'ऑटो-लोकेशन शेअरिंग',
    'settings.autoShareLocationDescription': 'आणीबाणीच्या इशाऱ्यामध्ये जीपीएस लोकेशन समाविष्ट करा',
    'settings.rideAutoStart': 'राइड ऑटो-स्टार्ट',
    'settings.rideAutoStartDescription': 'हालचाल आढळल्यास स्वयंचलितपणे देखरेख सुरू करा',
    'settings.offlineEmergencyMode': 'ऑफलाइन आणीबाणी मोड',
    'settings.offlineEmergencyModeDescription': 'इंटरनेट नसताना इशारे स्थानिक पातळीवर साठवा',
    'settings.pushNotifications': 'पुश सूचना',
    'settings.pushNotificationsDescription': 'राइड स्मरणपत्रे आणि सुरक्षितता इशारे',
    'settings.about': 'माहिती',
    'settings.medicalId': 'आणीबाणी वैद्यकीय आयडी',
    'settings.medicalIdDesc': 'आणीबाणीत सामायिक केलेले तुमचे वैद्यकीय तपशील पहा आणि संपादित करा',
    'settings.dangerZone': 'धोकादायक क्षेत्र',
    'settings.resetAllData': 'सर्व डेटा रिसेट करा',
    'settings.cancel': 'रद्द करा',
    'settings.resetEverything': 'सर्वकाही रिसेट करा',
    'settings.done': 'झाले',
    'home.title': 'होम',
    'home.rideActive': 'राइड सक्रिय',
    'home.readyToRide': 'राइडसाठी तयार',
    'contacts.title': 'संपर्क',
    'contacts.add': 'जोडा',
    'contacts.loading': 'संपर्क लोड होत आहेत...',
  },
  ta: {
    'tabs.home': 'முகப்பு',
    'tabs.ride': 'பயணம்',
    'tabs.contacts': 'தொடர்புகள்',
    'tabs.hospitals': 'மருத்துவமனைகள்',
    'tabs.settings': 'அமைப்புகள்',
    'settings.title': 'அமைப்புகள்',
    'settings.appearance': 'தோற்றம்',
    'settings.safety': 'பாதுகாப்பு',
    'settings.emergency': 'அவசரகாலம்',
    'settings.notifications': 'அறிவிப்புகள்',
    'settings.language': 'மொழி',
    'settings.languageDescription': 'பயன்பாட்டின் மொழியைத் தேர்ந்தெடுக்கவும்',
    'settings.themeDescription': 'இரவு 19:00 மணிக்கு மேல் கண்ணை கூசாமல் இருக்க சிவப்பு-கருப்பு தீம் தானாகவே செயல்படும்.',
    'settings.crashSensitivity': 'விபத்து கண்டறிதல் உணர்திறன்',
    'settings.crashSensitivityHint': 'அதிக உணர்திறன் லேசான தாக்கங்களையும் கண்டறியும். பரிந்துரை: நடுத்தரம்.',
    'settings.low': 'குறைந்த',
    'settings.medium': 'நடுத்தரம்',
    'settings.high': 'அதிக',
    'settings.sosDelay': 'SOS தானியங்கி அனுப்பும் தாமதம்',
    'settings.sosDelayDescription': 'எச்சரிக்கை தானாகவே அனுப்பப்படுவதற்கான வினாடிகள்',
    'settings.autoShareLocation': 'தானியங்கி இருப்பிடப் பகிர்வு',
    'settings.autoShareLocationDescription': 'அவசர எச்சரிக்கைகளில் ஜிபிஎஸ் இருப்பிடத்தை இணைக்கவும்',
    'settings.rideAutoStart': 'தானியங்கி பயணத் தொடக்கம்',
    'settings.rideAutoStartDescription': 'அசைவு கண்டறியப்பட்டதும் தானாகவே கண்காணிப்பைத் தொடங்கு',
    'settings.offlineEmergencyMode': 'ஆஃப்லைன் அவசர முறைமை',
    'settings.offlineEmergencyModeDescription': 'இணையம் இல்லாதபோது எச்சரிக்கைகளை உள்நாட்டில் சேமிக்கவும்',
    'settings.pushNotifications': 'புஷ் அறிவிப்புகள்',
    'settings.pushNotificationsDescription': 'பயண நினைவூட்டல்கள் மற்றும் பாதுகாப்பு எச்சரிக்கைகள்',
    'settings.about': 'பற்றி',
    'settings.medicalId': 'அவசர மருத்துவ ஐடி',
    'settings.medicalIdDesc': 'அவசரகாலத்தில் பகிரப்படும் முக்கிய மருத்துவ விவரங்களை திருத்தவும்',
    'settings.dangerZone': 'ஆபத்தான பகுதி',
    'settings.resetAllData': 'அனைத்து தரவையும் மீட்டமை',
    'settings.cancel': 'ரத்துசெய்',
    'settings.resetEverything': 'அனைத்தையும் மீட்டமை',
    'settings.done': 'முடிந்தது',
    'home.title': 'முகப்பு',
    'home.rideActive': 'பயணம் செயலில் உள்ளது',
    'home.readyToRide': 'பயணத்திற்கு தயார்',
    'contacts.title': 'தொடர்புகள்',
    'contacts.add': 'சேர்',
    'contacts.loading': 'தொடர்புகள் ஏற்றப்படுகின்றன...',
  },
  te: {
    'tabs.home': 'హోమ్',
    'tabs.ride': 'రైడ్',
    'tabs.contacts': 'పరిచయాలు',
    'tabs.hospitals': 'ఆసుపత్రులు',
    'tabs.settings': 'సెట్టింగ్స్',
    'settings.title': 'సెట్టింగ్స్',
    'settings.appearance': 'రూపం',
    'settings.safety': 'రక్షణ',
    'settings.emergency': 'అత్యవసర',
    'settings.notifications': 'నోటిఫికేషన్లు',
    'settings.language': 'భాష',
    'settings.languageDescription': 'యాప్ భాషను ఎంచుకోండి',
    'settings.themeDescription': 'రాత్రి 19:00 తర్వాత ఎరుపు-నలుపు నైట్ మోడ్ ఆటోమేటిక్‌గా యాక్టివేట్ అవుతుంది.',
    'settings.crashSensitivity': 'ప్రమాద గుర్తింపు సున్నితత్వం',
    'settings.crashSensitivityHint': 'ఎక్కువ సున్నితత్వం తేలికపాటి ప్రమాదాన్ని కూడా గుర్తిస్తుంది. రికమెండెడ్: మీడియం.',
    'settings.low': 'తక్కువ',
    'settings.medium': 'మీడియం',
    'settings.high': 'ఎక్కువ',
    'settings.sosDelay': 'SOS ఆటో-సెండ్ ఆలస్యం',
    'settings.sosDelayDescription': 'అలర్ట్ ఆటోమేటిక్‌గా వెళ్ళడానికి పట్టే సెకన్లు',
    'settings.autoShareLocation': 'ఆటో-లొకేషన్ షేరింగ్',
    'settings.autoShareLocationDescription': 'అత్యవసర అలర్ట్‌లలో జిపిఎస్ లొకేషన్‌ను చేర్చండి',
    'settings.rideAutoStart': 'రైడ్ ఆటో-స్టార్ట్',
    'settings.rideAutoStartDescription': 'కదలికను గుర్తించినప్పుడు ఆటోమేటిక్‌గా మానిటరింగ్ ప్రారంభించు',
    'settings.offlineEmergencyMode': 'ఆఫ్‌లైన్ అత్యవసర మోడ్',
    'settings.offlineEmergencyModeDescription': 'ఇంటర్నెట్ లేనప్పుడు అలర్ట్‌లను స్థానికంగా సేవ్ చేయి',
    'settings.pushNotifications': 'పుష్ నోటిఫికేషన్లు',
    'settings.pushNotificationsDescription': 'రైడ్ రిమైండర్లు మరియు రక్షణ అలర్ట్‌లు',
    'settings.about': 'గురించి',
    'settings.medicalId': 'అత్యవసర వైద్య ఐడి',
    'settings.medicalIdDesc': 'అత్యవసర సమయంలో షేర్ చేయబడే మీ వైద్య వివరాలను సవరించండి',
    'settings.dangerZone': 'డేంజర్ జోన్',
    'settings.resetAllData': 'మొత్తం యాప్ డేటాను రీసెట్ చేయి',
    'settings.cancel': 'రద్దు చేయి',
    'settings.resetEverything': 'అంతా రీసెట్ చేయి',
    'settings.done': 'పూర్తయింది',
    'home.title': 'హోమ్',
    'home.rideActive': 'రైడ్ యాక్టివ్‌గా ఉంది',
    'home.readyToRide': 'రైడ్ కోసం సిద్ధంగా ఉంది',
    'contacts.title': 'పరిచయాలు',
    'contacts.add': 'జోడించు',
    'contacts.loading': 'పరిచయాలు లోడ్ అవుతున్నాయి...',
  },
  bn: {
    'tabs.home': 'হোম',
    'tabs.ride': 'রাইড',
    'tabs.contacts': 'যোগাযোগ',
    'tabs.hospitals': 'হাসপাতাল',
    'tabs.settings': 'সেটিংস',
    'settings.title': 'সেটিংস',
    'settings.appearance': 'চেহারা',
    'settings.safety': 'নিরাপত্তা',
    'settings.emergency': 'জরুরী',
    'settings.notifications': 'বিজ্ঞপ্তি',
    'settings.language': 'ভাষা',
    'settings.languageDescription': 'অ্যাপের ভাষা নির্বাচন করুন',
    'settings.themeDescription': 'রাত ১৯:০০ টার পর উচ্চ-কন্ট্রাস্ট লাল-কালো নাইট মোড স্বয়ংক্রিয়ভাবে সক্রিয় হবে।',
    'settings.crashSensitivity': 'দুর্ঘটনা সনাক্তকরণ সংবেদনশীলতা',
    'settings.crashSensitivityHint': 'উচ্চ সংবেদনশীলতা হালকা ধাক্কাও সনাক্ত করতে পারে। প্রস্তাবিত: মাঝারি।',
    'settings.low': 'কম',
    'settings.medium': 'মাঝারি',
    'settings.high': 'উচ্চ',
    'settings.sosDelay': 'SOS অটো-সেন্ড বিলম্ব',
    'settings.sosDelayDescription': 'অ্যালার্ট স্বয়ংক্রিয়ভাবে পাঠানোর আগের সেকেন্ড',
    'settings.autoShareLocation': 'অটো-লোকেশন শেয়ারিং',
    'settings.autoShareLocationDescription': 'জরুরী অ্যালার্টের সাথে জিপিএস লোকেশন যুক্ত করুন',
    'settings.rideAutoStart': 'রাইড অটো-স্টার্ট',
    'settings.rideAutoStartDescription': 'গতি সনাক্ত হলে স্বয়ংক্রিয়ভাবে পর্যবেক্ষণ শুরু করুন',
    'settings.offlineEmergencyMode': 'অফলাইন জরুরী মোড',
    'settings.offlineEmergencyModeDescription': 'ইন্টারনেট না থাকলে অ্যালার্ট ডিভাইসে সেভ করুন',
    'settings.pushNotifications': 'পুশ বিজ্ঞপ্তি',
    'settings.pushNotificationsDescription': 'রাইড অনুস্মারক এবং নিরাপত্তা অ্যালার্ট',
    'settings.about': 'সম্পর্কে',
    'settings.medicalId': 'জরুরী মেডিকেল আইডি',
    'settings.medicalIdDesc': 'জরুরী অবস্থায় শেয়ার করা আপনার গুরুত্বপূর্ণ স্বাস্থ্য বিবরণ সম্পাদনা করুন',
    'settings.dangerZone': 'বিপদ অঞ্চল',
    'settings.resetAllData': 'অ্যাপের সমস্ত ডাটা রিসেট করুন',
    'settings.cancel': 'বাতিল করুন',
    'settings.resetEverything': 'সবকিছু রিসেট করুন',
    'settings.done': 'সম্পন্ন',
    'home.title': 'হোম',
    'home.rideActive': 'রাইড সক্রিয়',
    'home.readyToRide': 'রাইডের জন্য প্রস্তুত',
    'contacts.title': 'যোগাযোগ',
    'contacts.add': 'যুক্ত করুন',
    'contacts.loading': 'যোগাযোগ লোড হচ্ছে...',
  },
  kn: {
    'tabs.home': 'ಮುಖಪುಟ',
    'tabs.ride': 'ಸವಾರಿ',
    'tabs.contacts': 'ಸಂಪರ್ಕಗಳು',
    'tabs.hospitals': 'ಆಸ್ಪತ್ರೆಗಳು',
    'tabs.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.appearance': 'ಗೋಚರತೆ',
    'settings.safety': 'ಸುರಕ್ಷತೆ',
    'settings.emergency': 'ತುರ್ತು',
    'settings.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'settings.language': 'ಭಾಷೆ',
    'settings.languageDescription': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    'settings.themeDescription': 'ರಾತ್ರಿ 19:00 ರ ನಂತರ ಕೆಂಪು-ಕಪ್ಪು ನೈಟ್ ಮೋಡ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಕ್ರಿಯಗೊಳ್ಳುತ್ತದೆ.',
    'settings.crashSensitivity': 'ಅಪಘಾತ ಪತ್ತೆ ಸೂಕ್ಷ್ಮತೆ',
    'settings.crashSensitivityHint': 'ಹೆಚ್ಚಿನ ಸೂಕ್ಷ್ಮತೆಯು ಲಘು ಪರಿಣಾಮಗಳನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತದೆ. ಶಿಫಾರಸು: ಮಧ್ಯಮ.',
    'settings.low': 'ಕಡಿಮೆ',
    'settings.medium': 'ಮಧ್ಯಮ',
    'settings.high': 'ಹೆಚ್ಚು',
    'settings.sosDelay': 'SOS ಸ್ವಯಂ-ಕಳುಹಿಸುವ ವಿಳಂಬ',
    'settings.sosDelayDescription': 'ಎಚ್ಚರಿಕೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕಳುಹಿಸುವ ಮೊದಲಿನ ಸೆಕೆಂಡುಗಳು',
    'settings.autoShareLocation': 'ಸ್ವಯಂ-ಸ್ಥಳ ಹಂಚಿಕೆ',
    'settings.autoShareLocationDescription': 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳಲ್ಲಿ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಸೇರಿಸಿ',
    'settings.rideAutoStart': 'ಸವಾರಿ ಸ್ವಯಂ-ಪ್ರಾರಂಭ',
    'settings.rideAutoStartDescription': 'ಚಲನೆ ಪತ್ತೆಯಾದಾಗ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಮೇಲ್ವಿಚಾರಣೆ ಪ್ರಾರಂಭಿಸಿ',
    'settings.offlineEmergencyMode': 'ಆಫ್‌ಲೈನ್ ತುರ್ತು ಮೋಡ್',
    'settings.offlineEmergencyModeDescription': 'ಅಂತರ್ಜಾಲ ಲಭ್ಯವಿಲ್ಲದಿದ್ದಾಗ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಿ',
    'settings.pushNotifications': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
    'settings.pushNotificationsDescription': 'ಸವಾರಿ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಸುರಕ್ಷತಾ ಎಚ್ಚರಿಕೆಗಳು',
    'settings.about': 'ಕುರಿತು',
    'settings.medicalId': 'ತುರ್ತು ವೈದ್ಯಕೀಯ ಐಡಿ',
    'settings.medicalIdDesc': 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಲಾಗುವ ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ',
    'settings.dangerZone': 'ಅಪಾಯದ ವಲಯ',
    'settings.resetAllData': 'ಎಲ್ಲಾ ಡೇಟಾವನ್ನು ಮರುಹೊಂದಿಸಿ',
    'settings.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'settings.resetEverything': 'ಎಲ್ಲವನ್ನೂ ಮರುಹೊಂದಿಸಿ',
    'settings.done': 'ಮುಗಿದಿದೆ',
    'home.title': 'ಮುಖಪುಟ',
    'home.rideActive': 'ಸವಾರಿ ಸಕ್ರಿಯವಾಗಿದೆ',
    'home.readyToRide': 'ಸವಾರಿಗೆ ಸಿದ್ಧವಾಗಿದೆ',
    'contacts.title': 'ಸಂಪರ್ಕಗಳು',
    'contacts.add': 'ಸೇರಿಸಿ',
    'contacts.loading': 'ಸಂಪರ್ಕಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
  },
  ml: {
    'tabs.home': 'ഹോം',
    'tabs.ride': 'യാത്ര',
    'tabs.contacts': 'ബന്ധങ്ങൾ',
    'tabs.hospitals': 'ആശുപത്രികൾ',
    'tabs.settings': 'ക്രമീകരണങ്ങൾ',
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.appearance': 'രൂപം',
    'settings.safety': 'സുരക്ഷ',
    'settings.emergency': 'അടിയന്തിരം',
    'settings.notifications': 'അറിയിപ്പുകൾ',
    'settings.language': 'ഭാഷ',
    'settings.languageDescription': 'ആപ്പിലെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    'settings.themeDescription': 'രാത്രി 19:00 ന് ശേഷം ചുവപ്പ്-കറുപ്പ് നൈറ്റ് മോഡ് സ്വയം സജീവമാകും.',
    'settings.crashSensitivity': 'അപകട നിർണ്ണയ സംവേദനക്ഷമത',
    'settings.crashSensitivityHint': 'ഉയർന്ന സംവേദനക്ഷമത ചെറിയ ആഘാതങ്ങളും കണ്ടെത്തുന്നു. ശുപാർശ: ഇടത്തരം.',
    'settings.low': 'കുറഞ്ഞ',
    'settings.medium': 'ഇടത്തരം',
    'settings.high': 'ഉയർന്ന',
    'settings.sosDelay': 'SOS ഓട്ടോ-സെൻഡ് കാലതാമസം',
    'settings.sosDelayDescription': 'അലർട്ട് സ്വയമേവ അയക്കുന്നതിനുള്ള സെക്കൻഡുകൾ',
    'settings.autoShareLocation': 'ഓട്ടോ-ലൊക്കേഷൻ പങ്കിടൽ',
    'settings.autoShareLocationDescription': 'അടിയന്തിര അലർട്ടുകളിൽ ജിപിഎസ് ലൊക്കേഷൻ ഉൾപ്പെടുത്തുക',
    'settings.rideAutoStart': 'ഓട്ടോ യാത്ര ആരംഭം',
    'settings.rideAutoStartDescription': 'ചലനം കണ്ടെത്തിയാൽ ഉടൻ നിരീക്ഷണം ആരംഭിക്കുക',
    'settings.offlineEmergencyMode': 'ഓഫ്‌ലൈൻ അടിയന്തിര മോഡ്',
    'settings.offlineEmergencyModeDescription': 'ഇന്റർനെറ്റ് ലഭ്യമല്ലാത്തപ്പോൾ അലർട്ടുകൾ ഫോണിൽ സൂക്ഷിക്കുക',
    'settings.pushNotifications': 'പുഷ് അറിയിപ്പുകൾ',
    'settings.pushNotificationsDescription': 'യാത്രാ ഓർമ്മപ്പെടുത്തലുകളും സുരക്ഷാ അലർട്ടുകളും',
    'settings.about': 'വിവരം',
    'settings.medicalId': 'അടിയന്തിര മെഡിക്കൽ ഐഡി',
    'settings.medicalIdDesc': 'അടിയന്തിര ഘട്ടങ്ങളിൽ പങ്കിടുന്ന നിങ്ങളുടെ ആരോഗ്യ വിവരങ്ങൾ തിരുത്തുക',
    'settings.dangerZone': 'അപകട മേഖല',
    'settings.resetAllData': 'എല്ലാ വിവരങ്ങളും റീസെറ്റ് ചെയ്യുക',
    'settings.cancel': 'റദ്ദാക്കുക',
    'settings.resetEverything': 'എല്ലാം റീസെറ്റ് ചെയ്യുക',
    'settings.done': 'പൂർത്തിയായി',
    'home.title': 'ഹോം',
    'home.rideActive': 'യാത്ര സജീവമാണ്',
    'home.readyToRide': 'യാത്രയ്ക്ക് സജ്ജമാണ്',
    'contacts.title': 'ബന്ധങ്ങൾ',
    'contacts.add': 'ചേർക്കുക',
    'contacts.loading': 'ബന്ധങ്ങൾ ലഭ്യമാക്കുന്നു...',
  },
  pa: {
    'tabs.home': 'ਹੋਮ',
    'tabs.ride': 'ਸਵਾਰੀ',
    'tabs.contacts': 'ਸੰਪਰਕ',
    'tabs.hospitals': 'ਹਸਪਤਾਲ',
    'tabs.settings': 'ਸੈਟਿੰਗਜ਼',
    'settings.title': 'ਸੈਟਿੰਗਜ਼',
    'settings.appearance': 'ਦਿੱਖ',
    'settings.safety': 'ਸੁਰੱਖਿਆ',
    'settings.emergency': 'ਐਮਰਜੈਂਸੀ',
    'settings.notifications': 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
    'settings.language': 'ਭਾਸ਼ਾ',
    'settings.languageDescription': 'ਐਪ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'settings.themeDescription': 'ਰਾਤ 19:00 ਵਜੇ ਤੋਂ ਬਾਅਦ ਲਾਲ-ਕਾਲਾ ਨਾਈਟ ਮੋਡ ਆਪਣੇ ਆਪ ਐਕਟਿਵ ਹੋ ਜਾਵੇਗਾ।',
    'settings.crashSensitivity': 'ਹਾਦਸਾ ਪਛਾਣਨ ਦੀ ਸੰਵੇਦਨਸ਼ੀਲਤਾ',
    'settings.crashSensitivityHint': 'ਵੱਧ ਸੰਵੇਦਨਸ਼ੀਲਤਾ ਹਲਕੇ ਝਟਕੇ ਵੀ ਪਛਾਣਦੀ ਹੈ। ਸਿਫਾਰਸ਼: ਮੱਧਮ।',
    'settings.low': 'ਘੱਟ',
    'settings.medium': 'ਮੱਧਮ',
    'settings.high': 'ਉੱਚ',
    'settings.sosDelay': 'SOS ਆਟੋ-ਭੇਜਣ ਵਿੱਚ ਦੇਰੀ',
    'settings.sosDelayDescription': 'ਅਲਰਟ ਆਪਣੇ ਆਪ ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਦੇ ਸੈਕਿੰਡ',
    'settings.autoShareLocation': 'ਆਟੋ-ਲੋਕੇਸ਼ਨ ਸ਼ੇਅਰਿੰਗ',
    'settings.autoShareLocationDescription': 'ਐਮਰਜੈਂਸੀ ਅਲਰਟ ਵਿੱਚ ਜੀਪੀਐਸ ਲੋਕੇਸ਼ਨ ਸ਼ਾਮਲ ਕਰੋ',
    'settings.rideAutoStart': 'ਸਵਾਰੀ ਆਟੋ-ਸਟਾਰਟ',
    'settings.rideAutoStartDescription': 'ਹਿਲਜੁਲ ਮਹਿਸੂਸ ਹੋਣ ਤੇ ਆਪਣੇ ਆਪ ਨਿਗਰਾਨੀ ਸ਼ੁਰੂ ਕਰੋ',
    'settings.offlineEmergencyMode': 'ਆਫਲਾਈਨ ਐਮਰਜੈਂਸੀ ਮੋਡ',
    'settings.offlineEmergencyModeDescription': 'ਇੰਟਰਨੈਟ ਨਾ ਹੋਣ ਤੇ ਅਲਰਟ ਫੋਨ ਵਿੱਚ ਸੇਵ ਕਰੋ',
    'settings.pushNotifications': 'ਪੁਸ਼ ਨੋਟੀਫਿਕੇਸ਼ਨ',
    'settings.pushNotificationsDescription': 'ਸਵਾਰੀ ਰੀਮਾਈਂਡਰ ਅਤੇ ਸੁਰੱਖਿਆ ਅਲਰਟ',
    'settings.about': 'ਬਾਰੇ',
    'settings.medicalId': 'ਐਮਰਜੈਂਸੀ ਮੈਡੀਕਲ ਆਈਡੀ',
    'settings.medicalIdDesc': 'ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਸਾਂਝੇ ਕੀਤੇ ਜਾਣ ਵਾਲੇ ਆਪਣੇ ਡਾਕਟਰੀ ਵੇਰਵੇ ਸੋਧੋ',
    'settings.dangerZone': 'ਖਤਰਨਾਕ ਖੇਤਰ',
    'settings.resetAllData': 'ਸਾਰਾ ਐਪ ਡਾਟਾ ਰੀਸੈਟ ਕਰੋ',
    'settings.cancel': 'ਰੱਦ ਕਰੋ',
    'settings.resetEverything': 'ਸਭ ਕੁਝ ਰੀਸੈਟ ਕਰੋ',
    'settings.done': 'ਹੋ ਗਿਆ',
    'home.title': 'ਹੋਮ',
    'home.rideActive': 'ਸਵਾਰੀ ਐਕਟਿਵ ਹੈ',
    'home.readyToRide': 'ਸਵਾਰੀ ਲਈ ਤਿਆਰ',
    'contacts.title': 'ਸੰਪਰਕ',
    'contacts.add': 'ਜੋੜੋ',
    'contacts.loading': 'ਸੰਪਰਕ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
  },
  ur: {
    'tabs.home': 'ہوم',
    'tabs.ride': 'سفر',
    'tabs.contacts': 'رابطے',
    'tabs.hospitals': 'ہسپتال',
    'tabs.settings': 'سیٹنگز',
    'settings.title': 'سیٹنگز',
    'settings.appearance': 'ظاہری شکل',
    'settings.safety': 'حفاظت',
    'settings.emergency': 'ایمرجنسی',
    'settings.notifications': 'اطلاعات',
    'settings.language': 'زبان',
    'settings.languageDescription': 'ایپ کی زبان منتخب کریں',
    'settings.themeDescription': 'رات 19:00 کے بعد سرخ اور سیاہ نائٹ موڈ خود بخود فعال ہو جائے گا۔',
    'settings.crashSensitivity': 'حادثے کی حساسیت',
    'settings.crashSensitivityHint': 'زیادہ حساسیت ہلکے جھٹکوں کا بھی پتہ لگاتی ہے۔ تجویز کردہ: درمیانی۔',
    'settings.low': 'کم',
    'settings.medium': 'درمیانی',
    'settings.high': 'زیادہ',
    'settings.sosDelay': 'SOS خودکار بھیجنے کا وقت',
    'settings.sosDelayDescription': 'الرٹ خود بخود بھیجے جانے سے پہلے کے سیکنڈز',
    'settings.autoShareLocation': 'خودکار لوکیشن شیئرنگ',
    'settings.autoShareLocationDescription': 'ایمرجنسی الرٹ میں جی پی ایس لوکیشن شامل کریں',
    'settings.rideAutoStart': 'سفر خودکار آغاز',
    'settings.rideAutoStartDescription': 'حرکت محسوس ہونے پر خود بخود نگرانی شروع کریں',
    'settings.offlineEmergencyMode': 'آف لائن ایمرجنسی موڈ',
    'settings.offlineEmergencyModeDescription': 'انٹرنیٹ نہ ہونے پر الرٹس فون میں محفوظ کریں',
    'settings.pushNotifications': 'پش اطلاعات',
    'settings.pushNotificationsDescription': 'سفر کی یاد دہانی اور حفاظتی الرٹس',
    'settings.about': 'تفصیلات',
    'settings.medicalId': 'ایمرجنسی میڈیکل آئی ڈی',
    'settings.medicalIdDesc': 'ایمرجنسی میں شیئر کی جانے والی طبی تفصیلات کو تبدیل کریں',
    'settings.dangerZone': 'خطرناک زون',
    'settings.resetAllData': 'ایپ کا تمام ڈیٹا ری سیٹ کریں',
    'settings.cancel': 'منسوخ کریں',
    'settings.resetEverything': 'سب کچھ ری سیٹ کریں',
    'settings.done': 'مکمل',
    'home.title': 'ہوم',
    'home.rideActive': 'سفر جاری ہے',
    'home.readyToRide': 'سفر کے لیے تیار',
    'contacts.title': 'رابطے',
    'contacts.add': 'شامل کریں',
    'contacts.loading': 'رابطے لوڈ ہو رہے ہیں...',
  },
  es: {
    'tabs.home': 'Inicio',
    'tabs.ride': 'Viaje',
    'tabs.contacts': 'Contactos',
    'tabs.hospitals': 'Hospitales',
    'tabs.settings': 'Ajustes',
    'settings.title': 'Ajustes',
    'settings.appearance': 'APARIENCIA',
    'settings.safety': 'SEGURIDAD',
    'settings.emergency': 'EMERGENCIA',
    'settings.notifications': 'NOTIFICACIONES',
    'settings.language': 'Idioma',
    'settings.languageDescription': 'Elige el idioma de la aplicación',
    'settings.themeDescription': 'El modo automático activa una paleta nocturna roja y negra de alto contraste después de las 19:00.',
    'settings.crashSensitivity': 'Sensibilidad de choque',
    'settings.crashSensitivityHint': 'Una mayor sensibilidad detecta impactos más leves. Recomendado: Medio.',
    'settings.low': 'Bajo',
    'settings.medium': 'Medio',
    'settings.high': 'Alto',
    'settings.sosDelay': 'Retraso de envío automático SOS',
    'settings.sosDelayDescription': 'Segundos antes de que el alerta se envíe automáticamente',
    'settings.autoShareLocation': 'Compartir ubicación automática',
    'settings.autoShareLocationDescription': 'Incluye coordenadas GPS en las alertas de emergencia',
    'settings.rideAutoStart': 'Inicio automático del viaje',
    'settings.rideAutoStartDescription': 'Comienza el monitoreo automáticamente al detectar movimiento',
    'settings.offlineEmergencyMode': 'Modo de emergencia sin conexión',
    'settings.offlineEmergencyModeDescription': 'Pone las alertas en cola localmente cuando internet no está disponible',
    'settings.pushNotifications': 'Notificaciones push',
    'settings.pushNotificationsDescription': 'Recordatorios de viaje y alertas de seguridad',
    'settings.about': 'ACERCA DE',
    'settings.medicalId': 'Identificación médica de emergencia',
    'settings.medicalIdDesc': 'Ver y editar los detalles médicos compartidos en un SOS',
    'settings.dangerZone': 'Zona de peligro',
    'settings.resetAllData': 'Restablecer todos los datos',
    'settings.cancel': 'Cancelar',
    'settings.resetEverything': 'Restablecer todo',
    'settings.done': 'Hecho',
    'home.title': 'Inicio',
    'home.rideActive': 'Viaje activo',
    'home.readyToRide': 'Listo para rodar',
    'contacts.title': 'Contactos',
    'contacts.add': 'Añadir',
    'contacts.loading': 'Cargando contactos...',
  },
  fr: {
    'tabs.home': 'Accueil',
    'tabs.ride': 'Trajet',
    'tabs.contacts': 'Contacts',
    'tabs.hospitals': 'Hôpitaux',
    'tabs.settings': 'Paramètres',
    'settings.title': 'Paramètres',
    'settings.appearance': 'APPARENCE',
    'settings.safety': 'SÉCURITÉ',
    'settings.emergency': 'URGENCE',
    'settings.notifications': 'NOTIFICATIONS',
    'settings.language': 'Langue',
    'settings.languageDescription': 'Choisissez la langue de l’application',
    'settings.themeDescription': 'Le mode automatique active un thème nocturne rouge et noir à haut contraste après 19h00.',
    'settings.crashSensitivity': 'Sensibilité aux chocs',
    'settings.crashSensitivityHint': 'Une sensibilité accrue détecte les impacts plus légers. Recommandé : Moyen.',
    'settings.low': 'Faible',
    'settings.medium': 'Moyen',
    'settings.high': 'Élevée',
    'settings.sosDelay': 'Délai d’envoi automatique SOS',
    'settings.sosDelayDescription': 'Secondes avant l’envoi automatique de l’alerte',
    'settings.autoShareLocation': 'Partage de position automatique',
    'settings.autoShareLocationDescription': 'Inclure les coordonnées GPS dans les alertes d’urgence',
    'settings.rideAutoStart': 'Démarrage automatique du trajet',
    'settings.rideAutoStartDescription': 'Commencer le suivi automatiquement lors de la détection de mouvement',
    'settings.offlineEmergencyMode': 'Mode d’urgence hors ligne',
    'settings.offlineEmergencyModeDescription': 'Mettre les alertes en file d’attente locale en l’absence d’internet',
    'settings.pushNotifications': 'Notifications push',
    'settings.pushNotificationsDescription': 'Rappels de trajet et alertes de sécurité',
    'settings.about': 'À PROPOS',
    'settings.medicalId': 'Identité médicale d’urgence',
    'settings.medicalIdDesc': 'Consulter et modifier les informations médicales partagées en SOS',
    'settings.dangerZone': 'Zone de danger',
    'settings.resetAllData': 'Réinitialiser toutes les données',
    'settings.cancel': 'Annuler',
    'settings.resetEverything': 'Réinitialiser tout',
    'settings.done': 'Terminé',
    'home.title': 'Accueil',
    'home.rideActive': 'Trajet actif',
    'home.readyToRide': 'Prêt à partir',
    'contacts.title': 'Contacts',
    'contacts.add': 'Ajouter',
    'contacts.loading': 'Chargement des contacts...',
  },
  de: {
    'tabs.home': 'Startseite',
    'tabs.ride': 'Fahrt',
    'tabs.contacts': 'Kontakte',
    'tabs.hospitals': 'Krankenhäuser',
    'tabs.settings': 'Einstellungen',
    'settings.title': 'Einstellungen',
    'settings.appearance': 'DESIGNS',
    'settings.safety': 'SICHERHEIT',
    'settings.emergency': 'NOTFALL',
    'settings.notifications': 'MITTEILUNGEN',
    'settings.language': 'Sprache',
    'settings.languageDescription': 'Wählen Sie die App-Sprache aus',
    'settings.themeDescription': 'Der Automatikmodus aktiviert nach 19:00 Uhr ein kontrastreiches rot-schwarzes Nachtdesign.',
    'settings.crashSensitivity': 'Unfallempfindlichkeit',
    'settings.crashSensitivityHint': 'Höhere Empfindlichkeit erkennt leichtere Stöße. Empfohlen: Mittel.',
    'settings.low': 'Niedrig',
    'settings.medium': 'Mittel',
    'settings.high': 'Hoch',
    'settings.sosDelay': 'SOS-Sende-Verzögerung',
    'settings.sosDelayDescription': 'Sekunden bis zum automatischen Senden des Alarms',
    'settings.autoShareLocation': 'Automatisches Teilen des Standorts',
    'settings.autoShareLocationDescription': 'GPS-Koordinaten in Notfallalarmen mitsenden',
    'settings.rideAutoStart': 'Automatischer Start der Fahrt',
    'settings.rideAutoStartDescription': 'Überwachung automatisch starten, wenn Bewegung erkannt wird',
    'settings.offlineEmergencyMode': 'Offline-Notfallmodus',
    'settings.offlineEmergencyModeDescription': 'Alarme lokal in Warteschlange stellen, wenn kein Internet vorhanden ist',
    'settings.pushNotifications': 'Push-Benachrichtigungen',
    'settings.pushNotificationsDescription': 'Fahrterinnerungen und Sicherheitswarnungen',
    'settings.about': 'INFO',
    'settings.medicalId': 'Notfall-Medizinischer Ausweis',
    'settings.medicalIdDesc': 'Im Notfall geteilte medizinische Details anzeigen und bearbeiten',
    'settings.dangerZone': 'Gefahrenzone',
    'settings.resetAllData': 'Alle App-Daten zurücksetzen',
    'settings.cancel': 'Abbrechen',
    'settings.resetEverything': 'Alles zurücksetzen',
    'settings.done': 'Fertig',
    'home.title': 'Startseite',
    'home.rideActive': 'Fahrt aktiv',
    'home.readyToRide': 'Bereit zur Fahrt',
    'contacts.title': 'Kontakte',
    'contacts.add': 'Hinzufügen',
    'contacts.loading': 'Kontakte werden geladen...',
  },
  ar: {
    'tabs.home': 'الرئيسية',
    'tabs.ride': 'رحلة',
    'tabs.contacts': 'جهات الاتصال',
    'tabs.hospitals': 'المستشفيات',
    'tabs.settings': 'الإعدادات',
    'settings.title': 'الإعدادات',
    'settings.appearance': 'المظهر',
    'settings.safety': 'الأمان',
    'settings.emergency': 'الطوارئ',
    'settings.notifications': 'الإشعارات',
    'settings.language': 'اللغة',
    'settings.languageDescription': 'اختر اللغة المستخدمة في التطبيق',
    'settings.themeDescription': 'يفعل الوضع التلقائي سمة ليلية عالية التباين باللونين الأحمر والأسود بعد الساعة 19:00.',
    'settings.crashSensitivity': 'حساسية الاصطدام',
    'settings.crashSensitivityHint': 'الحساسية الأعلى تكتشف الصدمات الأخف. الموصى به: متوسط.',
    'settings.low': 'منخفض',
    'settings.medium': 'متوسط',
    'settings.high': 'عالي',
    'settings.sosDelay': 'تأخير الإرسال التلقائي لـ SOS',
    'settings.sosDelayDescription': 'الثواني قبل إرسال التنبيه تلقائيًا',
    'settings.autoShareLocation': 'مشاركة الموقع تلقائيًا',
    'settings.autoShareLocationDescription': 'تضمين إحداثيات GPS في تنبيهات الطوارئ',
    'settings.rideAutoStart': 'بدء الرحلة تلقائيًا',
    'settings.rideAutoStartDescription': 'بدء المراقبة تلقائيًا عند اكتشاف الحركة',
    'settings.offlineEmergencyMode': 'وضع الطوارئ دون اتصال',
    'settings.offlineEmergencyModeDescription': 'جدولة التنبيهات محليًا عند عدم توفر الإنترنت',
    'settings.pushNotifications': 'إشعارات الهاتف',
    'settings.pushNotificationsDescription': 'تذكيرات الرحلات وتنبيهات السلامة',
    'settings.about': 'حول التطبيق',
    'settings.medicalId': 'الهوية الطبية للطوارئ',
    'settings.medicalIdDesc': 'عرض وتعديل التفاصيل الطبية الهامة التي تُشارك أثناء الطوارئ',
    'settings.dangerZone': 'منطقة الخطر',
    'settings.resetAllData': 'إعادة تعيين جميع بيانات التطبيق',
    'settings.cancel': 'إلغاء',
    'settings.resetEverything': 'إعادة تعيين كل شيء',
    'settings.done': 'تم',
    'home.title': 'الرئيسية',
    'home.rideActive': 'الرحلة نشطة',
    'home.readyToRide': 'جاهز للانطلاق',
    'contacts.title': 'جهات الاتصال',
    'contacts.add': 'إضافة',
    'contacts.loading': 'جارٍ تحميل جهات الاتصال...',
  },
  ja: {
    'tabs.home': 'ホーム',
    'tabs.ride': '走行',
    'tabs.contacts': '緊急連絡先',
    'tabs.hospitals': '救急病院',
    'tabs.settings': '設定',
    'settings.title': '設定',
    'settings.appearance': '外観設定',
    'settings.safety': '安全機能',
    'settings.emergency': '緊急対応',
    'settings.notifications': '通知設定',
    'settings.language': '言語設定',
    'settings.languageDescription': 'アプリで使用する言語を選択してください',
    'settings.themeDescription': '自動モードでは、19:00以降に目の疲労を軽減する高コントラストの赤黒ナイトテーマが有効になります。',
    'settings.crashSensitivity': '衝突検知の感度',
    'settings.crashSensitivityHint': '感度を高く設定すると、軽微な衝撃も検知します。推奨：中。',
    'settings.low': '低',
    'settings.medium': '中',
    'settings.high': '高',
    'settings.sosDelay': 'SOS自動送信までの遅延時間',
    'settings.sosDelayDescription': '自動的にアラートが送信されるまでの秒数',
    'settings.autoShareLocation': '位置情報の自動共有',
    'settings.autoShareLocationDescription': '緊急アラートにGPS座標を含める',
    'settings.rideAutoStart': '走行自動検知スタート',
    'settings.rideAutoStartDescription': '動きを感知した際に、自動的に安全監視を開始します',
    'settings.offlineEmergencyMode': 'オフライン緊急モード',
    'settings.offlineEmergencyModeDescription': 'インターネット未接続時、一時的にアラートをローカルにキュー保存します',
    'settings.pushNotifications': 'プッシュ通知',
    'settings.pushNotificationsDescription': '安全アラートや走行リマインダーの通知',
    'settings.about': 'アプリについて',
    'settings.medicalId': '緊急メディカルID',
    'settings.medicalIdDesc': '緊急SOSの際に送信される重要な医療情報の確認と編集',
    'settings.dangerZone': '危険ゾーン',
    'settings.resetAllData': 'すべてのアプリデータを初期化する',
    'settings.cancel': 'キャンセル',
    'settings.resetEverything': 'すべてをリセットする',
    'settings.done': '完了',
    'home.title': 'ホーム',
    'home.rideActive': '監視中 · 走行中',
    'home.readyToRide': '走行準備完了',
    'contacts.title': '緊急連絡先',
    'contacts.add': '追加する',
    'contacts.loading': '連絡先を読み込み中...',
  },
  zh: {
    'tabs.home': '首页',
    'tabs.ride': '骑行',
    'tabs.contacts': '紧急联系',
    'tabs.hospitals': '救急医院',
    'tabs.settings': '设置',
    'settings.title': '设置',
    'settings.appearance': '外观设置',
    'settings.safety': '安全监控',
    'settings.emergency': '紧急联络',
    'settings.notifications': '通知消息',
    'settings.language': '语言选择',
    'settings.languageDescription': '选择应用于应用程序的语言',
    'settings.themeDescription': '自动模式会在19:00之后开启高对比度的红黑夜间护眼模式。',
    'settings.crashSensitivity': '碰撞碰撞检测敏感度',
    'settings.crashSensitivityHint': '较高的灵敏度会检测到轻微的冲击。推荐：中。',
    'settings.low': '低',
    'settings.medium': '中',
    'settings.high': '高',
    'settings.sosDelay': 'SOS自动发送延时',
    'settings.sosDelayDescription': '紧急警报自动发送前的倒计时秒数',
    'settings.autoShareLocation': '自动分享实时位置',
    'settings.autoShareLocationDescription': '在紧急警报中自动附加您的GPS经纬度',
    'settings.rideAutoStart': '骑行状态自动识别',
    'settings.rideAutoStartDescription': '在检测到明显运动时自动开启安全守护监视',
    'settings.offlineEmergencyMode': '离线紧急离线模式',
    'settings.offlineEmergencyModeDescription': '无网络连接时，将警报保存在本地发送队列中',
    'settings.pushNotifications': '消息推送服务',
    'settings.pushNotificationsDescription': '骑行行程提醒与主动安全提示',
    'settings.about': '关于我们',
    'settings.medicalId': '紧急个人医疗卡',
    'settings.medicalIdDesc': '查看和编辑在紧急救援时自动发送的健康/过敏史数据',
    'settings.dangerZone': '危险警戒区域',
    'settings.resetAllData': '清除并恢复所有应用数据',
    'settings.cancel': '取消',
    'settings.resetEverything': '重置所有',
    'settings.done': '完成',
    'home.title': '首页',
    'home.rideActive': '安全监视中',
    'home.readyToRide': '骑行守护已就绪',
    'contacts.title': '紧急联系',
    'contacts.add': '添加联系人',
    'contacts.loading': '联系人加载中...',
  },
};

interface LocalizationContextValue {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: TranslationKey) => string;
}

const LocalizationContext = createContext<LocalizationContextValue | undefined>(undefined);

export function LocalizationProvider({ children }: { children: ReactNode }): React.JSX.Element {
  const [language, setLanguageState] = useState<AppLanguage>(DEFAULT_PREFERENCES.language);

  useEffect(() => {
    async function loadPreferences(): Promise<void> {
      const result = await StorageService.get<UserPreferences>(STORAGE_KEYS.PREFERENCES);
      if (result.success && result.data?.language) {
        setLanguageState(result.data.language);
      }
    }

    void loadPreferences();
  }, []);

  async function setLanguage(languageCode: AppLanguage): Promise<void> {
    setLanguageState(languageCode);

    const result = await StorageService.get<UserPreferences>(STORAGE_KEYS.PREFERENCES);
    const preferences = result.success && result.data ? result.data : DEFAULT_PREFERENCES;

    await StorageService.set(STORAGE_KEYS.PREFERENCES, {
      ...preferences,
      language: languageCode,
    });
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey) => translations[language][key] ?? baseEnglishTranslations[key],
    }),
    [language],
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useTranslation(): LocalizationContextValue {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useTranslation must be used within LocalizationProvider.');
  }
  return context;
}

